name: domain
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  dio: ^4.0.6
  hydrated_bloc: ^8.1.0
  hive: ^2.1.0
  freezed: ^2.1.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.5.2
